### ISSUE TITLE
accessing neighboring elements via refs or component object

### ISSUE THREAD

**Issue by matthewmueller** [ashaffer/virtex#2]
Not sure if there's a good way to access an input right now. React has refs (https://github.com/dekujs/deku/blob/e2ffd467b8404001da2121c7b6d173bbc9715d1e/docs/examples/iteration/react.js#L36) and it looks like deku gives you access to the component (https://github.com/dekujs/deku/blob/e2ffd467b8404001da2121c7b6d173bbc9715d1e/docs/examples/iteration/index.js#L40)

Do you have any plans to add something like this?

**Comment by ashaffer** [comment]
I have a pretty strong preference for minimizing direct access to DOM nodes and values in general that are external.  If you just want to get its value, i'd say to do an `onChange` and set the value into your app's state.  I'll be creating a solution for local state soon that should make that simpler.

Does that address the use case you have in mind?

**Comment by matthewmueller** [comment]
> If you just want to get its value, i'd say to do an onChange and set the value into your app's state. I'll be creating a solution for local state soon that should make that simpler.

yep, that's perfect :-)
