### ISSUE TITLE
requires need @micro-js/is-string

### ISSUE THREAD

**Issue by matthewmueller** [ashaffer/virtex#3]
looks like those files are placed into the scope @micro-js, so I think they'd need to be:

``` js
require('@micro-js/is-string')
require('@micro-js/is-undefined')
require('@micro-js/foreach')
```

also, is there any plans to version these guys? you should be able to do: `@micro-js/is-string: "1.0.0"`

**Comment by matthewmueller** [comment]
nvm, looks like you're moving everything back over to vdux :-D

**Comment by ashaffer** [comment]
Ya, I had originally been not scoping them.

virtex and vdux are independent. I am about to start using virtex inside of vdux, in place of virtual-dom though :-), hopefully i'll merge that into master this weekend.

**Comment by matthewmueller** [comment]
woah inception, can you explain quick what the goal of each project is then? I thought they were side-by-side, is vdux higher-level?

**Comment by ashaffer** [comment]
vdux I have been thinking of as like a super tiny framework that creates the state <-> vdom loop. Originally I was just using virtual-dom, but there wasn't a nice way to deal with pseudo-local state, so virtex is an alternative virtual-dom (or virtual-anything, really - it is intended to be able to support native backends in the future) that just allows solving the local state problem in a nicer way, by letting redux middleware thread state from the primary state atom back into the components as they're rendered.

virtex is strictly a virtual dom, vdux is concerned with the higher-level application update loop.

**Comment by matthewmueller** [comment]
okay awesome :-D

so it sounds like i'd use vdux if i was starting a client-side app today ;-)

**Comment by ashaffer** [comment]
Ya definitely. vdux is what I intend most people to use. But all of the interesting stuff happens in the middleware, so you should still be able to extend virtex significantly even while using the higher-level construct.

The idea is to keep all of the opinionated things (local state, components, rendering backend) in the middleware, so that all of that stuff can be interceded in and manipulated.
